package net.message;

/**
 * an enum class for the message types that need to be handled
 *
 * @author ygarip not completed yet
 */
public enum MessageType {
  DISCONNECT, // DONE
  STARTGAME, // DONE
  PLAYERREADY, // DONE
  CONNECT, // DONE
  CHATMESSAGE, // DONE
  UPDATEGAMEBOARD, // DONE
  SUBMITMOVE, // DONE
  UPDATEPOINTS, // DONE
  SENDPLAYERDATA, // DONE
  GETTILE, // DONE
  EXCHANGETILES, // DONE
  UPDATEGAMESETTINGS, // DONE
  REFUSECONNECTION, // DONE
  ADDAI, // DONE
  KICKPLAYER, // DONE
  EXCEEDEDTIME,
  REQUESTVALUES,
  REQUESTDISTRIBUTIONS,
  REQUESTDICTIONARY,
  PLACETILE
}
